
import OpenAI from 'openai';
import { OPENAI_API_KEY } from '../../config/constants';

// Initialize and export OpenAI client with better error handling
export const initializeOpenAI = () => {
  // Enhanced API key validation
  if (!OPENAI_API_KEY || OPENAI_API_KEY.trim() === '') {
    console.error("OPENAI_API_KEY is missing or empty");
    throw new Error('OpenAI API key is missing or empty. Please check your Supabase secrets.');
  }
  
  console.log("Initializing OpenAI with API key (first few chars):", 
    OPENAI_API_KEY ? `${OPENAI_API_KEY.substring(0, 5)}...` : "MISSING");

  return new OpenAI({
    apiKey: OPENAI_API_KEY,
    dangerouslyAllowBrowser: true  // Required for client-side usage
  });
};

// Function to generate content using OpenAI with improved error handling
export const generateAIContent = async (
  systemPrompt: string, 
  userPrompt: string,
  options = { temperature: 0.7, maxTokens: 1500 }
): Promise<string> => {
  try {
    console.log('Initializing OpenAI client');
    const openai = initializeOpenAI();
    
    console.log('Calling OpenAI API with system prompt and user prompt');
    console.log('System prompt:', systemPrompt);
    console.log('User prompt length:', userPrompt.length);
    
    // Use the configured API key from Supabase secrets
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini", // Using a supported model
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: options.temperature,
      max_tokens: options.maxTokens
    });

    console.log('OpenAI Response received:', response.choices[0]?.finish_reason);

    // Extract and validate generated text
    const generatedText = response.choices[0]?.message?.content?.trim();
    
    if (!generatedText) {
      throw new Error('No content was generated by the AI. Please try again.');
    }
    
    console.log('Generated text length:', generatedText.length);
    
    return generatedText;
  } catch (error) {
    console.error('Error generating AI content:', error);
    
    // More informative error handling
    if (error instanceof OpenAI.APIError) {
      console.error('OpenAI API Error details:', error.status, error.message);
      
      if (error.status === 401) {
        throw new Error(`Authentication error: Invalid API key. Please check your OpenAI API key in Supabase secrets.`);
      } else if (error.status === 429) {
        throw new Error(`Rate limit exceeded: ${error.message}. Please try again in a few moments.`);
      } else if (error.status === 500) {
        throw new Error(`OpenAI server error: ${error.message}. Please try again later.`);
      } else {
        throw new Error(`OpenAI API Error (${error.status}): ${error.message}`);
      }
    }
    
    throw new Error(`Failed to generate content: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};
