// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrruxjftdzvwlbjfuiew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxycnV4amZ0ZHp2d2xiamZ1aWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Mjc4NjUsImV4cCI6MjA1OTMwMzg2NX0.C2MeFAyYb4mS3ucuuQpMA-ClthcfR__NDaDX0vNq8JU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);